### ISSUE TITLE
Can i use this library for loading web service data while entering text

### ISSUE THREAD

**Issue by kprathap23** [mirrajabi/search-dialog#1]
Like Google maps Search box to load dynamic web service data..

**Comment by mirrajabi** [comment]
Yeah sure.
I will provide an example for it and update the sample app soon

**Comment by mirrajabi** [comment]
The sample app is updated and now has a sample for online data fetching. You may want to update the version to `1.1` now cause loading progress was added recently.

I'm sure there are better ways to do this, if anyone has a better suggestion just send a PR and i will gladly check it.
