### ISSUE TITLE
Cannot filter ...

### ISSUE THREAD

**Issue by sakil007** [mirrajabi/search-dialog#10]
Every thing is ok but it cannot filter ..What can i do?

**Comment by mirrajabi** [comment]
Have you followed all the instructions correctly? 
https://github.com/mirrajabi/search-dialog#simple-usage

**Comment by Oirere-Jr** [comment]
Same here. Filtering not working.

**Comment by Nixforest** [comment]
Same here. Just follow simple usage, but can not filter :(

**Comment by mirrajabi** [comment]
Thanks for the feedback guys. I'll check it in my spare time.

**Comment by mirrajabi** [comment]
Have you also checked version 1.2.1?

**Comment by Nixforest** [comment]
I checked on 1.2.1, it's worked.
implementation 'com.github.mirrajabi:search-dialog:1.2.1'

**Comment by mirrajabi** [comment]
@sakil007 @Oirere-Jr can you also check and then close the issue if it works?

**Comment by Oirere-Jr** [comment]
worked like a charm. Thanks.

**Comment by Nixforest** [comment]
Hi mirrajabi,
Can you help me how to use SimpleSearchFilter object for constructor:
I tried:
`SimpleSearchFilter< SampleSearchModel > filter = new SimpleSearchFilter<>(
               createSampleData(),
                new FilterResultListener() {
                    @Override
                    public void onFilter(ArrayList arrayList) {
                        // What's I should write here?
                    }
                }
        );
new SimpleSearchDialogCompat(MainActivity.this, "Search...",
                        "What are you looking for...?", filter, createSampleData(),
                        new SearchResultListener<SampleSearchModel>() {
                            @Override
                            public void onSelected(BaseSearchDialogCompat dialog,
                                                   SampleSearchModel item, int position) {
                                Toast.makeText(MainActivity.this, item.getTitle(),
                                        Toast.LENGTH_SHORT).show();
                                dialog.dismiss();
                            }
                        }).show();`
My purpose is I want to overriding SimpleSearchFilter.performFiltering method to change logic when filter keyword.
Thanks in advance.
Nixforest

**Comment by mirrajabi** [comment]
Hi @Nixforest,
This question is not related to the subject but I'll answer briefly.
You don't have to do anything with the `SimpleSearchFilter`. What you should do is to make another class and extend the [BaseFilter](https://github.com/mirrajabi/search-dialog/blob/master/library/src/main/java/ir/mirrajabi/searchdialog/core/BaseFilter.java) class.

Something like this:
```java
public class CustomSearchFilter extends BaseFilter {

    @Override
    protected FilterResults performFiltering(CharSequence chars) {
        // return the results here
    }

    @Override
    protected void publishResults(CharSequence constraint, FilterResults results) {
    }
}
```

For a more detailed sample see [SimpleSearchFilter](https://github.com/mirrajabi/search-dialog/blob/master/library/src/main/java/ir/mirrajabi/searchdialog/SimpleSearchFilter.java)'s implementation.
