### ISSUE TITLE
multi selection?

### ISSUE THREAD

**Issue by nicemak** [mirrajabi/search-dialog#13]
is that possible to select multiple entries?

**Comment by mirrajabi** [comment]
Hi,
Not at the moment.

**Comment by prscX** [comment]
Thanks @mirrajabi for providing very needful & cool library.

It would be nice to enable multiple selection capability. Please let me know incase you are planning work on this, or I can take this in my free time.

@nicemak 

Thanks
</ Pranav >

**Comment by mirrajabi** [comment]
@prscX Hi,

I don't think I'll be able to work on it anytime soon. so If you can, please do.

**Comment by mirrajabi** [comment]
@prscX any updates?

**Comment by prscX** [comment]
@mirrajabi: Due to other items on the plate, I was not able to pick this item. Are you planning to enable this feature?

Thanks
</ Pranav >
