### ISSUE TITLE
The search filter not working correctly

### ISSUE THREAD

**Issue by behrooz-fard** [mirrajabi/search-dialog#14]
I search for some specific word but the true result is not the first filter result. Like this:
![screenshot_2018-09-11-12-10-53-627_com onlinejoo app](https://user-images.githubusercontent.com/23365261/45345668-40c60b00-b5bc-11e8-9275-c47ddc45e061.png)

**Comment by mirrajabi** [comment]
Give v1.2.3 a try and let me know if it's working.
Cheers
