### ISSUE TITLE
How do I change list item(Arraylist) specific  text color

### ISSUE THREAD

**Issue by molekulyazilim** [mirrajabi/search-dialog#15]
Hello,

First, thank you for this good library.

I populate the list from the database(sqlite). I just want to change the color of some items value. For example; one of value from database is "RED" at the same time I should change that index text color to red. How can i do this.

**Comment by mirrajabi** [comment]
Hi,
Please read This section of readme: https://github.com/mirrajabi/search-dialog#the-adapter
You can write your custom adapters if you want more flexibility.
