### ISSUE TITLE
Increase search dialog size

### ISSUE THREAD

**Issue by SkyGanfor** [mirrajabi/search-dialog#17]
Is there anyway to increase the size of the search dialog? It would help a lot in landscape mode as it only takes up a fraction of the screen.

**Comment by mirrajabi** [comment]
Well you can override the layout like this:
1. copy the dialog layout file from (here)[https://github.com/mirrajabi/search-dialog/blob/master/library/src/main/res/layout/search_dialog_compat.xml] and put it in your layout resources directory (keeping the same file name and all the ids in it)
2. Change sizes, colors, texts...
