### ISSUE TITLE
Optional parameter to define whether touching the title closes the dialog or not

### ISSUE THREAD

**Issue by juandfranco** [mirrajabi/search-dialog#18]
Hello, this function would be perfect if you make it optional since it is uncomfortable for some users with large fingers, many times they close the dialogue by accident

`view.findViewById(R.id.dummy_background)
			.setOnClickListener(new View.OnClickListener() {
				@Override
				public void onClick(View view) {
					dismiss();
				}
			});`

**Comment by mirrajabi** [comment]
Hi,
Which title do you mean?

**Comment by juandfranco** [comment]
Hi, when you click on dummy_background when you are too close to the title, the dialogue closes, a persistence parameter would be good, if you do not want it to close when you tap outside the dialog,

dialog.setCancelable (false)
dialog.setCanceledOnTouchOutside (false)

they work correctly, but not when you touch on dummy_background since you have the code that I put in the previous comment

**Comment by mirrajabi** [comment]
Sorry, it took a while. I added this option to v1.2.4
I still think the touch-outside handlings are not quite good but I just don't have enough time to improve it.
The project really needs a big update/refactor.
