### ISSUE TITLE
The library overrides the search icon

### ISSUE THREAD

**Issue by alashow** [mirrajabi/search-dialog#2]
Hey.

Thanks for your library!

I have a search icon in my app with name "ic_search". When I use your library, my search icon is being replaced with the icon included in the library.
I guess you just need to add a prefix, like: `search_dialog_ic_search.png`.

**Comment by mirrajabi** [comment]
@alashow Thanks for the fix.

**Comment by alashow** [comment]
Could you please release a new version, so we can pull it from jitpack?

**Comment by mirrajabi** [comment]
you can go with `compile 'com.github.mirrajabi:search-dialog:e83ad764f6'`

**Comment by alashow** [comment]
Sure, but it would be better if I use proper release version (like 1.1 or 1.2) instead of git hash.

**Comment by mirrajabi** [comment]
@alashow ok go with `1.1.1`
