### ISSUE TITLE
Proguard 

### ISSUE THREAD

**Issue by mayurteraiya** [mirrajabi/search-dialog#21]
i have implement this library in my entire project. but i have also added proguard in app.

When i used sign apk it's not working...

Can you please share proguard rules for that .

Waiting for your quick replay.

Thanks

**Comment by mirrajabi** [comment]
Hey,
Do you have any crashlogs? How do you know this library is causing the issue?

**Comment by mayurteraiya** [comment]
it's not crashing. but when we use proguard it's does't open search dialog when i click on it.

just implement proguard in your sample and check it if possible. and if you can invest time for this.

**Comment by mirrajabi** [comment]
I enabled proguard with no extra setup in debug mode:
```

android {
    ...
    buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
       ...
    }
    ...
}
```
 and I cannot reproduce the issue.
