### ISSUE TITLE
How can I change row layout inside recyclerview?

### ISSUE THREAD

**Issue by pratikbutani** [mirrajabi/search-dialog#22]
I want to change the row layout of RecyclerView. I want to display more data instead of "title", Can you suggest me how can I change that layout?

**Comment by mirrajabi** [comment]
The answer [is already in project readme. ](https://github.com/mirrajabi/search-dialog#advanced-usage)

**Comment by pratikbutani** [comment]
> The answer [is already in project readme. ](https://github.com/mirrajabi/search-dialog#advanced-usage)

I am talking about row layout of recyclerview. Can you please give me example. How can I pass custom layout?
