### ISSUE TITLE
change font color

### ISSUE THREAD

**Issue by irsalshabirin** [mirrajabi/search-dialog#4]
please help me, to change font color

**Comment by mirrajabi** [comment]
@irsalshabirin library has been updated to 1.2 and sample app has some updated lines.
check it out
https://github.com/mirrajabi/search-dialog/blob/master/app/src/main/java/ir/mirrajabi/searchdialog/sample/MainActivity.java#L64

**Comment by irsalshabirin** [comment]
@mirrajabi but how i can change font color from recyclerView ?

**Comment by irsalshabirin** [comment]
how about change font color recyclerView ?
maybe, from constructor SimpleSearchDialogCompat() we can set a style from `styles.xml`

**Comment by mirrajabi** [comment]
Show me exactly what do you want to change so I can help you.

**Comment by irsalshabirin** [comment]
I already change my activity with this style 
```
<style name="AppTheme.ActionBar">
        <item name="colorPrimary">#96781f</item>
        <item name="colorPrimaryDark">#96781f</item>
        <item name="colorAccent">#96781f</item>

        <item name="android:textColorPrimary">@android:color/white</item>
        <item name="android:textColorSecondary">@android:color/black</item>
        ....
</style>
```

and the result like this :
![ezgif com-optimize](https://user-images.githubusercontent.com/4993269/27829658-d1b221b0-60ec-11e7-8300-25bb754c35da.gif)
font from recyclerView  can not be seen

I'm sorry before. I also use this library https://github.com/afollestad/material-dialogs, Background color can adjust. result like this :
![screenshot_2017-07-04-19-18-08-128_alidien co](https://user-images.githubusercontent.com/4993269/27829849-d14a0520-60ed-11e7-9f6c-d3848b6a7b1e.png)
note : I did not change the color settings in the "material-dialogs"


thanks before

**Comment by mirrajabi** [comment]
I guess this is what you were looking for.
Go with `1.2.1` and take a look at [here](https://github.com/mirrajabi/search-dialog#changing-default-adapters-text-colorsadded-in-v121)

**Comment by irsalshabirin** [comment]
thanks 👍  👍  👍
