### ISSUE TITLE
not getting filtered

### ISSUE THREAD

**Issue by yoonusc** [mirrajabi/search-dialog#7]
Hi

I implemented your library in my app which have a activity and tow tabs using tab layout view pager and fragment but everything is working right  but the list not getting filtered while typing in search box I why this happen any clue

**Comment by DevUnderos** [comment]
@yoonusc  Try use old version,  v1.1 works without filter bugs.

**Comment by yoonusc** [comment]
Oky thanks

On Dec 12, 2017 10:49 PM, "Hayk Avanesyan" <notifications@github.com> wrote:

@yoonusc <https://github.com/yoonusc> Try use old version, v1.1 works
without filter bugs.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mirrajabi/search-dialog/issues/7#issuecomment-351121224>,
or mute the thread

**Comment by yoonusc** [comment]
hello that's fixed i used older version 1.1 its work fine and not working
your latest version along with tab layout fragment view pager

thanks

**Comment by bhavikmehta5491** [comment]
Please fix this issue in 1.2 as well.
Thanks OP for questioning this here
